services:
  db:
    image: postgres:16-alpine
    restart: always
    networks:
      - back_net
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: production
    networks:
      - front_net
      - back_net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "8080:80"
    networks:
      - front_net
    depends_on:
      - backend

networks:
  front_net:
  back_net:

volumes:
  db_data: